// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type User struct {
	ID        int32
	Username  string
	Password  string
	Firstname sql.NullString
	Lastname  sql.NullString
	Dob       sql.NullString
	City      sql.NullString
	State     sql.NullString
}
