// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type User struct {
	UserID    int32
	UserName  string
	Password  []byte
	FirstName sql.NullString
	LastName  sql.NullString
	Dob       sql.NullString
	City      sql.NullString
	State     sql.NullString
}
